= Projekt Plan

== Ausgangspunkt

Für dieses Projekt war ich inspiriert als ich mit meiner Familie zusammen Monopoly auf der Nintendo Switch gespielt habe.
Weil ich aber kein Künstler bin habe ich mich entschieden die Darstellung komplett in der Konsole zu machen.

Ursprünglich wollte ich das Spiel in python schreiben um etwas neues zu lernen, aber das erwies sich als zu schwierig, weil meine python Fähigkeiten für ein so komplexes Projekt unzureichend sind. (Wobei ich mittlerweile überzeugt bin, dass es unmöglich ist etwas halbwegs komplexes mit python zu schreiben).
Das bisherige python Projekt nutze ich jetzt wie einen Prototypen, bei dem ich viel über die Struktur gelernt habe aber ich fange dennoch von vorne an.
Der Link zum alten Repo ist https://github.com/orjules/MonopolyConsole[hier].


== Plan

Um später einfacher Verbesserungen hinzufügen zu können, ist das Programm so modular wie möglich erstellt.
Einige Klassen wie "Tabelle" oder "Würfel" stehen ganz für sich alleine.
Der "Darsteller" darf als einziger Text ein- und ausgeben. Das ermöglicht in Zukunft das hinzufügen eines Multiplayers oder eines grafischen Interfaces.
Am stärksten Verknüpft ist der "Organisator", der mit den Klassen im "System"-Package arbeitet aber extern nur mit jeweils einer Klassen pro Package.

=== Klassendiagramm

image::https://github.com/orjules/MonopolyJava/blob/coreRedesign/Dokumentation/KlassendiagrammeExporte/Klassendiagramm_neusterStand.svg[Das Klassendiagramm]

Das Programm ist in drei Teile unterteilt:

- System (Beinhaltet die Logik für den Spielablauf)

- Karten (Verantwortlich für zufällige sowie spezielle Aktionen)

- Grundstücke (Verwaltet die Informationen über Grundstückbesitze und wie viel was kostet)



image::https://github.com/orjules/MonopolyJava/blob/coreRedesign/Dokumentation/NeueArchitekturExporte/NeueArchitektur1.svg[Das neue Klassendiagramm]

Das neue System nutzt eine Design Idee aus der "Clean Code" Video Reihe von Robert Martin. 

Es gibt nun eine bessere Trennung zwischen UI und System. Ziel ist es das System Package so umzuschreiben, dass im System keine Strings generiert werden, sondern nur ein Modell, dass alle Daten enthält um die String auszulesen. Dadurch kann die Darstellung später leicht angepasst werden. Außerdem wird der klarere Ablauf von Eingabe zu Eingabe-Modell zu Systemreaktion zu Ausgabe-Modell zu Ausgabe das Zwischenschalten von Server Kommunikation erleichtern.


=== State Diagramm

image::https://github.com/orjules/MonopolyJava/blob/coreRedesign/Dokumentation/StateDiagramm%20Exporte/State%20Diagramm2.svg[Das neue Klassendiagramm]

Für das neue Design will ich das State Pattern nutzen. 

Monopoly hat 8 States:
- Erster Wurf (Wenn ein Spieler seinen Zug beginnt und nicht im Gefängnis ist, muss man würfeln)
- Auf freiem Grundstück gelandet (nach einem Wurf kann man auf einem kaufbaren Grundstück landen)
- Versteigern (Wenn man auf einem freien Grundstück gelandet ist, aber es nicht kaufen will)
- Auf besetztem Grunstück gelandet (nach einem Wurf kann auf einem Grundstück landen wo man Miete zahlen muss)
- Karte ziehen (nach einem Wurf kann man auf einem Feld landen wo etwas spezielles passiert oder nichts. So oder so muss man bestätigen)
- Übersicht (Zeigt die eine Übersicht über den eigenen Besitz und ermöglicht das Handeln mit anderen)
- Zu wenig Geld (Wenn man Miete oder bei einer Karte zahlen muss aber nicht genug Geld hat)
- Alles erledigt (Wenn man alles auf dem neuen Feld erledigt hat und keinen pasch hatte)
- Im Gefängnis (Es gibt mehrere Arten ins Gefängnis zu gehen und herauszukommen)


=== Aktivitätsdiagramm

image::https://github.com/orjules/MonopolyJava/blob/coreRedesign/Dokumentation/AktivitätsdiagrammExporte/gameLoop_MitPackages.svg[Das Aktivitätsdiagramm]

Weil der Hauptloop des Spieles so kompliziert ist, habe ich ihn zur Übersicht in ein Diagramm übertragen. (Noch nicht vollständig


== Fortschritt

=== 9.3.21

- Repo und Projekt erstellt
- Ersten Entwurf von python Prototyp übernommen
- Würfel implementiert
- Brett zeichnen mit aktuellen Spielerpositionen
- Erste Version der Bewegung

=== 10.3.21

- Prototyp für GameLoop erstellt und überarbeitet
- Weitere Klassen erstellt
- Interfaces und Mocks für Integrationtest erstellt

=== 11.3.21

- Interfaces, Mocks und Integrationtest entfernt (weil sie mehr arbeit gemacht haben als gespart)
- Darstellung überarbeitet
- Akzeptable, lauffähige Version erstellt und somut Meilenstein "Spieler bewegen" erreicht
- Dokumentation verbessert

=== 12.3.21

- Erkennen auf welchem Feld man landet implementiert
- Grundstücke kaufen und Miete zahlen implementiert
- Aktivitätsdiagramm überarbeitet

=== 13.3.21

- Refactorisiert
- Versucht Tests zu schreiben
- Klassendiagramm angepasst

=== 18.3.21

- Funktionierenden Prototyp für die Karten erstellt

=== 1.4.21

- Tests für alles außer System erstellt
- Erkannt, dass das System Package nicht gut designed ist und erneuert werden muss
- Ersten Plan für das Redesign erstellt

=== 2.4.21

- Bei Testen und implementieren des Redesigns sind einige Probleme aufgefallen, was zu einem neuen Redesign geführt hat
- Neuer Plan ist ähnlich dem ersten Redesign aber mit dem State Pattern im Herzen vom System

Als nächstes: System mit State Pattern neu schreiben mit besserer Entkoppelung und Testgetrieben
