= Projekt Plan

== Ausgangspunkt

Für dieses Projekt war ich inspiriert als ich mit meiner Familie zusammen Monopoly auf der Nintendo Switch gespielt habe.
Weil ich aber kein Künstler bin habe ich mich entschieden die Darstellung komplett in der Konsole zu machen.

Ursprünglich wollte ich das Spiel in python schreiben um etwas neues zu lernen, aber das erwies sich als zu schwierig, weil meine python Fähigkeiten für ein so komplexes Projekt unzureichend sind. (Wobei ich mittlerweile überzeugt bin, dass es unmöglich ist etwas halbwegs komplexes mit python zu schreiben).
Das bisherige python Projekt nutze ich jetzt wie einen Prototypen, bei dem ich viel über die Struktur gelernt habe aber ich fange dennoch von vorne an.
Der Link zum alten Repo ist https://github.com/orjules/MonopolyConsole[hier].


== Plan

Um später einfacher Verbesserungen hinzufügen zu können, ist das Programm so modular wie möglich erstellt.
Einige Klassen wie "Tabelle" oder "Würfel" stehen ganz für sich alleine.
Der "Darsteller" darf als einziger Text ein- und ausgeben. Das ermöglicht in Zukunft das hinzufügen eines Multiplayers oder eines grafischen Interfaces.
Am stärksten Verknüpft ist der "Organisator", der mit den Klassen im "System"-Package arbeitet aber extern nur mit jeweils einer Klassen pro Package.

=== Klassendiagramm

image::https://github.com/orjules/MonopolyJava/blob/Bewegung/Dokumentation/Entwurf/Entwurf1_SystemFertig.svg[Das Klassendiagramm]

Das Programm ist in drei Teile unterteilt:

- System (Beinhaltet die Logik für den Spielablauf)

- Karten (Verantwortlich für zufällige sowie spezielle Aktionen)

- Grundstücke (Verwaltet die Informationen über Grundstückbesitze und wie viel was kostet)

=== Aktivitätsdiagramm

image::https://github.com/orjules/MonopolyJava/blob/kaufenUndBewegung/Dokumentation/Entwurf/gameLoop_MitPackages.svg[Das Aktivitätsdiagramm]

Weil der Hauptloop des Spieles so kompliziert ist, habe ich ihn zur Übersicht in ein Diagramm übertragen. (Noch nicht vollständig)

== Fortschritt

=== 9.3.21

- Repo und Projekt erstellt

- Ersten Entwurf von python Prototyp übernommen

- Würfel implementiert

- Brett zeichnen mit aktuellen Spielerpositionen

- Erste Version der Bewegung

=== 10.3.21

- Prototyp für GameLoop erstellt und überarbeitet

- Weitere Klassen erstellt

- Interfaces und Mocks für Integrationtest erstellt

=== 11.3.21

- Interfaces, Mocks und Integrationtest entfernt (weil sie mehr arbeit gemacht haben als gespart)

- Darstellung überarbeitet

- Akzeptable, lauffähige Version erstellt und somut Meilenstein "Spieler bewegen" erreicht

- Dokumentation verbessert

Als nächstes: Tests für fertige Klassen im "System"-Package erstellen
